### ISSUE TITLE
Graphics are not copyable

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#42] opened 2017-01-26 12:57 UTC
1. When selecting and copying the whole output or single graphic ["right-click", "Select all" and "Copy"], then only the text will be copied.

Example (OpenOffice 4 Writer):

![bug5](https://cloud.githubusercontent.com/assets/22355317/22332092/560e3f0c-e3cf-11e6-86fd-6eafadb19a31.jpg)

2. As PDF stored graphics can’t be copied too (from PDF to LibreOffice 5.1 Writer):

![bug6](https://cloud.githubusercontent.com/assets/22355317/22332485/7896652a-e3d1-11e6-82c9-bb57cc400424.jpg)

<i>Used Software: Adobe Acrobat Reader DC 2015, Word 2010, OpenOffice 4, LibreOffice 5.1</i>
<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by krajcsi** [comment] 2017-02-23 12:58
1. Th CS > OO copy problem is a duplicate of #4 

2. The Adobe Reader > Writer problem must be some pdf reader specific thing. I never saw this issue with Evince pdf reader and various LibreOffice versions in Linux. Could you try it with some other pdf reader(s) (or with e.g., LibreOffice Draw)?

**Comment by RRP89** [comment] 2017-05-30 06:54
2. You are right: It's a pdf reader specific problem. When using LibreOffice Draw it works (see graphic). But a new bug is upcoming: see under [Issue](https://github.com/cogstat/cogstat/issues/43).

**Comment by krajcsi** [comment] 2021-07-29 11:34
With solving #4, the first part of this issue is also solved.

**Closed by krajcsi** 2021-07-29 11:34 UTC
Labels: bug, chart
